require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('./models/User');
const Event = require('./models/Event');
const Booking = require('./models/Booking');
const SavedEvent = require('./models/SavedEvent');

const seedData = async () => {
    try {
        console.log('Seeding Database...');

        // Clear existing data
        await User.deleteMany({});
        await Event.deleteMany({});
        await Booking.deleteMany({});
        await SavedEvent.deleteMany({});
        console.log('Cleared existing data');

        // Create users (unified role — everyone can host & join)
        const alex = await User.create({
            name: 'Alex Organizer',
            email: 'alex@interplay.com',
            password: 'password123',
        });

        const sam = await User.create({
            name: 'Sam Player',
            email: 'sam@interplay.com',
            password: 'password123',
        });

        const priya = await User.create({
            name: 'Priya Sports',
            email: 'priya@interplay.com',
            password: 'password123',
        });

        const raj = await User.create({
            name: 'Raj Kumar',
            email: 'raj@interplay.com',
            password: 'password123',
        });

        console.log('✅ Users created');

        // Create sample events — all in Tamil Nadu, dates between April 15 – June 30, 2026
        // Each of the 38 districts has at least 1–2 events
        const events = await Event.insertMany([
            // ══════════════════════════════════════════════════════════════
            // ORIGINAL EVENTS (updated with district field)
            // ══════════════════════════════════════════════════════════════
            {
                title: 'Inter-City Football Championship 2026',
                sport: 'football',
                description: 'Join the biggest football tournament of the year! Open for teams of all skill levels. Compete against the best and win exciting prizes.\n\nFormat: 5-a-side\nPrize Pool: ₹50,000\nSlots: 16 teams',
                date: new Date('2026-04-18T09:00:00'),
                location: 'Jawaharlal Nehru Stadium, Chennai',
                district: 'Chennai',
                registrationLink: '',
                price: 500,
                totalSlots: 16,
                availableSlots: 12,
                organizerId: alex._id,
                isTournament: false,
                coordinates: { lat: 13.0614, lng: 80.2350 },
            },
            {
                title: 'Weekend Cricket League — Season 3',
                sport: 'cricket',
                description: 'The Weekend Cricket League is back! Register your team for Season 3. Matches every Saturday and Sunday.\n\nFormat: T20\nTeams: 8 max\nEntry: ₹2,000 per team',
                date: new Date('2026-04-25T07:00:00'),
                location: 'M. A. Chidambaram Stadium, Chennai',
                district: 'Chennai',
                registrationLink: 'https://forms.gle/example123',
                price: 2000,
                totalSlots: 8,
                availableSlots: 5,
                organizerId: alex._id,
                isTournament: false,
                coordinates: { lat: 13.0627, lng: 80.2792 },
            },
            {
                title: 'Badminton Open Singles Tournament',
                sport: 'badminton',
                description: 'Test your skills at the Badminton Open! Individual singles tournament with multiple age categories.\n\nCategories: U-19, Open, 35+\nEntry Fee: ₹500',
                date: new Date('2026-05-02T10:00:00'),
                location: 'SDAT Tennis Stadium, Coimbatore',
                district: 'Coimbatore',
                registrationLink: '',
                price: 500,
                totalSlots: 32,
                availableSlots: 18,
                organizerId: alex._id,
                isTournament: false,
                coordinates: { lat: 11.0168, lng: 76.9558 },
            },
            {
                title: 'Corporate Basketball 3x3 Cup',
                sport: 'basketball',
                description: 'A 3x3 basketball tournament exclusively for corporate teams. Network, compete, and have fun!\n\nFormat: 3x3 Half-court\nPrize: Trophy + Gift Vouchers',
                date: new Date('2026-05-16T16:00:00'),
                location: 'Indoor Stadium, Madurai',
                district: 'Madurai',
                registrationLink: 'https://forms.gle/example123',
                price: 0,
                totalSlots: 20,
                availableSlots: 20,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 9.9252, lng: 78.1198 },
            },
            {
                title: 'Summer Tennis Championship',
                sport: 'tennis',
                description: 'Annual summer tennis championship. Singles and doubles categories available. AITA ranking points applicable.\n\nSurface: Hard Court\nDraw: 32 players',
                date: new Date('2026-05-30T08:00:00'),
                location: 'SDAT Complex, Trichy',
                district: 'Tiruchirappalli',
                registrationLink: '',
                price: 1500,
                totalSlots: 32,
                availableSlots: 4,
                organizerId: alex._id,
                isTournament: false,
                coordinates: { lat: 10.7905, lng: 78.7047 },
            },
            {
                title: 'Beach Volleyball Bash',
                sport: 'volleyball',
                description: 'Hit the sand for a fun-filled beach volleyball tournament! Register as a duo.\n\nFormat: 2v2 Beach Volleyball\nEntry: Free\nPrizes: Medals + Goodies',
                date: new Date('2026-06-07T06:30:00'),
                location: 'Marina Beach, Chennai',
                district: 'Chennai',
                registrationLink: '',
                price: 0,
                totalSlots: 0,
                availableSlots: 0,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 13.0500, lng: 80.2824 },
            },
            {
                title: 'Midnight Football Pickup — Looking for Players!',
                sport: 'football',
                description: 'Casual 7-a-side football game at midnight. All skill levels welcome. Just show up and play!\n\nBring your own boots.\nWater will be provided.',
                date: new Date('2026-06-13T23:30:00'),
                location: 'Nehru Park, Salem',
                district: 'Salem',
                registrationLink: '',
                price: 0,
                totalSlots: 14,
                availableSlots: 3,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 11.6643, lng: 78.1460 },
            },
            {
                title: "Women's Cricket Tournament — Spring Edition",
                sport: 'cricket',
                description: "An exclusive women's cricket tournament celebrating talent and sportsmanship.\n\nFormat: T10\nTeams: 6\nPrize: ₹25,000 + Trophies",
                date: new Date('2026-04-20T08:00:00'),
                location: 'SNR College Grounds, Coimbatore',
                district: 'Coimbatore',
                registrationLink: 'https://forms.gle/example123',
                price: 1000,
                totalSlots: 6,
                availableSlots: 2,
                organizerId: alex._id,
                isTournament: false,
                coordinates: { lat: 11.0048, lng: 76.9610 },
            },
            // College Tournaments (original)
            {
                title: 'SSN College Football Tournament',
                sport: 'football',
                description: 'The annual SSN College Inter-Department Football Tournament is here! Form your team and battle it out on the field.\n\nFormat: 11-a-side\nOpen to all SSN students & alumni\nTeam Registration Required\n\nPrize Pool: ₹30,000\nWinners Trophy + Individual Medals',
                date: new Date('2026-05-10T09:00:00'),
                location: 'SSN College of Engineering, Kalavakkam, Chennai',
                district: 'Chengalpattu',
                registrationLink: 'https://forms.gle/example123',
                price: 300,
                totalSlots: 12,
                availableSlots: 5,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 12.7519, lng: 80.1980 },
            },
            {
                title: 'VIT Chennai Cricket League',
                sport: 'cricket',
                description: 'VIT Chennai presents its flagship Cricket League! Compete in the T20 format across multiple weekends.\n\nFormat: T20 League\nOpen to VIT students & partner colleges\nTeam Registration Required\n\nPrize: ₹40,000 + Rolling Trophy',
                date: new Date('2026-05-17T07:30:00'),
                location: 'VIT Chennai Campus, Vandalur, Chennai',
                district: 'Chengalpattu',
                registrationLink: 'https://forms.gle/example123',
                price: 500,
                totalSlots: 8,
                availableSlots: 3,
                organizerId: sam._id,
                isTournament: true,
                coordinates: { lat: 12.8406, lng: 80.1534 },
            },
            {
                title: 'SRM Badminton Championship',
                sport: 'badminton',
                description: "SRM Institute of Science and Technology hosts the Annual Badminton Championship.\n\nCategories: Men's Singles, Women's Singles, Men's Doubles\nOpen to all college students in Tamil Nadu\nTeam Registration Required\n\nPrize: Medals + Certificates + Cash Awards",
                date: new Date('2026-06-01T10:00:00'),
                location: 'SRM University, Kattankulathur, Chennai',
                district: 'Chengalpattu',
                registrationLink: 'https://forms.gle/example123',
                price: 200,
                totalSlots: 48,
                availableSlots: 20,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 12.8231, lng: 80.0442 },
            },
            {
                title: 'Anna University Basketball Cup',
                sport: 'basketball',
                description: 'The prestigious Anna University Inter-College Basketball Cup returns this summer!\n\nFormat: 5v5 Full Court\nOpen to Anna University affiliated colleges\nTeam Registration Required\n\nPrize Pool: ₹25,000\nBest Player Award',
                date: new Date('2026-06-14T15:00:00'),
                location: 'Anna University, Guindy, Chennai',
                district: 'Chennai',
                registrationLink: 'https://forms.gle/example123',
                price: 0,
                totalSlots: 16,
                availableSlots: 8,
                organizerId: sam._id,
                isTournament: true,
                coordinates: { lat: 13.0108, lng: 80.2354 },
            },

            // ══════════════════════════════════════════════════════════════
            // NEW EVENTS — covering all 38 Tamil Nadu districts
            // ══════════════════════════════════════════════════════════════

            // --- Ariyalur ---
            {
                title: 'Ariyalur District Football League',
                sport: 'football',
                description: 'Annual district-level football league open to all local clubs and school teams.\n\nFormat: 11-a-side\nPrize: ₹15,000 + Trophy',
                date: new Date('2026-05-03T08:00:00'),
                location: 'Government Sports Ground, Ariyalur',
                district: 'Ariyalur',
                price: 0,
                totalSlots: 12,
                availableSlots: 8,
                organizerId: raj._id,
                isTournament: true,
                coordinates: { lat: 11.1400, lng: 79.0782 },
            },
            {
                title: 'Ariyalur Cricket Carnival',
                sport: 'cricket',
                description: 'Weekend cricket carnival with T10 format. Open to all ages.\n\nFree entry. Refreshments provided.',
                date: new Date('2026-05-17T07:00:00'),
                location: 'Ariyalur Town Cricket Ground',
                district: 'Ariyalur',
                price: 0,
                totalSlots: 8,
                availableSlots: 4,
                organizerId: priya._id,
                isTournament: false,
                coordinates: { lat: 11.1420, lng: 79.0770 },
            },

            // --- Cuddalore ---
            {
                title: 'Cuddalore Coastal Cricket Cup',
                sport: 'cricket',
                description: 'Inter-ward cricket tournament near the coast. T20 format with live commentary.\n\nPrize Pool: ₹20,000',
                date: new Date('2026-04-26T07:30:00'),
                location: 'Manjakuppam Sports Complex, Cuddalore',
                district: 'Cuddalore',
                price: 300,
                totalSlots: 10,
                availableSlots: 6,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 11.7480, lng: 79.7714 },
            },
            {
                title: 'Casual Badminton Evening — Cuddalore',
                sport: 'badminton',
                description: 'Casual badminton games every Friday evening. All levels welcome. Rackets available on-site.',
                date: new Date('2026-05-08T17:00:00'),
                location: 'District Indoor Stadium, Cuddalore',
                district: 'Cuddalore',
                price: 0,
                totalSlots: 16,
                availableSlots: 10,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 11.7500, lng: 79.7680 },
            },

            // --- Dharmapuri ---
            {
                title: 'Dharmapuri Inter-School Basketball',
                sport: 'basketball',
                description: 'Annual inter-school basketball championship organized by District Sports Authority.\n\nCategories: Boys U-17, Girls U-17',
                date: new Date('2026-05-10T09:00:00'),
                location: 'Government Higher Secondary School Ground, Dharmapuri',
                district: 'Dharmapuri',
                price: 0,
                totalSlots: 16,
                availableSlots: 12,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 12.1274, lng: 78.1573 },
            },
            {
                title: 'Sunday Football Kickabout — Dharmapuri',
                sport: 'football',
                description: 'Casual Sunday morning football. 7-a-side, open to all.\nJust come and play!',
                date: new Date('2026-05-24T06:00:00'),
                location: 'Nehru Stadium, Dharmapuri',
                district: 'Dharmapuri',
                price: 0,
                totalSlots: 14,
                availableSlots: 6,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 12.1290, lng: 78.1600 },
            },

            // --- Dindigul ---
            {
                title: 'Dindigul District Badminton Championship',
                sport: 'badminton',
                description: 'Open District Badminton Championship. Singles & Doubles.\n\nEntry: ₹200 per player\nPrize: Medals + Cash Awards',
                date: new Date('2026-05-09T09:30:00'),
                location: 'YMCA Indoor Hall, Dindigul',
                district: 'Dindigul',
                price: 200,
                totalSlots: 48,
                availableSlots: 30,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 10.3673, lng: 77.9803 },
            },
            {
                title: 'Dindigul Night Cricket Bash',
                sport: 'cricket',
                description: 'Floodlit night cricket with box format. Great atmosphere, great cricket!\n\nFormat: Box Cricket (6-a-side)',
                date: new Date('2026-06-05T20:00:00'),
                location: 'KVB Grounds, Dindigul',
                district: 'Dindigul',
                price: 100,
                totalSlots: 12,
                availableSlots: 5,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 10.3650, lng: 77.9820 },
            },

            // --- Erode ---
            {
                title: 'Erode Premier Football League',
                sport: 'football',
                description: 'City-level football league played over 4 weekends. Professional referees.\n\nFormat: 11-a-side League\nPrize Pool: ₹40,000',
                date: new Date('2026-05-01T15:00:00'),
                location: 'VOC Ground, Erode',
                district: 'Erode',
                price: 500,
                totalSlots: 8,
                availableSlots: 3,
                organizerId: raj._id,
                isTournament: true,
                coordinates: { lat: 11.3410, lng: 77.7172 },
            },
            {
                title: 'Erode Shuttle Stars — Badminton',
                sport: 'badminton',
                description: 'Weekly badminton meetup for enthusiasts. Coaching tips from certified coaches available.\n\nAll skill levels welcome.',
                date: new Date('2026-05-15T18:00:00'),
                location: 'Perundurai Indoor Stadium, Erode',
                district: 'Erode',
                price: 0,
                totalSlots: 20,
                availableSlots: 14,
                organizerId: priya._id,
                isTournament: false,
                coordinates: { lat: 11.2780, lng: 77.5880 },
            },

            // --- Kallakurichi ---
            {
                title: 'Kallakurichi Youth Cricket Tournament',
                sport: 'cricket',
                description: 'Open youth cricket tournament. Under-23 category.\n\nFormat: T20\nTeams: 8\nPrize: ₹10,000 + Medals',
                date: new Date('2026-05-23T07:00:00'),
                location: 'Government Grounds, Kallakurichi',
                district: 'Kallakurichi',
                price: 200,
                totalSlots: 8,
                availableSlots: 5,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 11.7380, lng: 78.9592 },
            },
            {
                title: 'Pickup Football — Kallakurichi',
                sport: 'football',
                description: 'Casual evening football. Looking for players to join our weekly games!',
                date: new Date('2026-06-10T17:00:00'),
                location: 'Municipal Ground, Kallakurichi',
                district: 'Kallakurichi',
                price: 0,
                totalSlots: 14,
                availableSlots: 8,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 11.7400, lng: 78.9600 },
            },

            // --- Kanchipuram ---
            {
                title: 'Kanchipuram Heritage Basketball Cup',
                sport: 'basketball',
                description: 'Inter-ward basketball tournament in the temple city.\n\nFormat: 5v5\nPrize: ₹15,000',
                date: new Date('2026-05-11T08:30:00'),
                location: 'District Sports Complex, Kanchipuram',
                district: 'Kanchipuram',
                price: 0,
                totalSlots: 12,
                availableSlots: 6,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 12.8342, lng: 79.7036 },
            },
            {
                title: 'Kanchipuram Cricket — Weekend Pickup',
                sport: 'cricket',
                description: 'Casual weekend cricket in the heart of Kanchipuram. Grab your bat and join us!',
                date: new Date('2026-06-07T07:00:00'),
                location: 'Pachaiyappas Ground, Kanchipuram',
                district: 'Kanchipuram',
                price: 0,
                totalSlots: 22,
                availableSlots: 10,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 12.8350, lng: 79.7050 },
            },

            // --- Kanniyakumari ---
            {
                title: 'Cape Football Fiesta',
                sport: 'football',
                description: 'Football tournament at the southern tip of India! Open to all adult teams.\n\nFormat: 7-a-side\nPrize: ₹25,000 + Trophy',
                date: new Date('2026-05-17T08:00:00'),
                location: 'Scott Christian College, Nagercoil',
                district: 'Kanniyakumari',
                price: 300,
                totalSlots: 16,
                availableSlots: 10,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 8.1833, lng: 77.4119 },
            },
            {
                title: 'Nagercoil Evening Badminton',
                sport: 'badminton',
                description: 'Friendly badminton games every Wednesday evening. All levels welcome.',
                date: new Date('2026-05-27T17:30:00'),
                location: 'Indoor Stadium, Nagercoil',
                district: 'Kanniyakumari',
                price: 0,
                totalSlots: 16,
                availableSlots: 12,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 8.1830, lng: 77.4120 },
            },

            // --- Karur ---
            {
                title: 'Karur District Cricket Championship',
                sport: 'cricket',
                description: 'Annual district-level cricket championship organized by TNCA.\n\nFormat: 50-over\nTeams: 8',
                date: new Date('2026-05-05T08:00:00'),
                location: 'Municipal Corporation Ground, Karur',
                district: 'Karur',
                price: 0,
                totalSlots: 8,
                availableSlots: 3,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 10.9601, lng: 78.0766 },
            },
            {
                title: 'Karur Pickup Basketball',
                sport: 'basketball',
                description: '3x3 pickup basketball games. Come with your squad or join as an individual!',
                date: new Date('2026-05-31T16:30:00'),
                location: 'Corporation Higher Secondary School, Karur',
                district: 'Karur',
                price: 0,
                totalSlots: 12,
                availableSlots: 8,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 10.9610, lng: 78.0780 },
            },

            // --- Krishnagiri ---
            {
                title: 'Krishnagiri Mango Cup Football',
                sport: 'football',
                description: 'The famous Mango Cup returns! Football tournament during mango season.\n\nFormat: 11-a-side\nPrize: ₹30,000 + 🥭',
                date: new Date('2026-06-01T07:00:00'),
                location: 'Government Stadium, Krishnagiri',
                district: 'Krishnagiri',
                price: 200,
                totalSlots: 16,
                availableSlots: 10,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 12.5186, lng: 78.2138 },
            },
            {
                title: 'Hosur Corporate Cricket League',
                sport: 'cricket',
                description: 'Corporate cricket league for IT companies in Hosur. Weekend T20 matches.\n\nEntry: ₹3,000 per team',
                date: new Date('2026-05-09T08:00:00'),
                location: 'SIPCOT Grounds, Hosur',
                district: 'Krishnagiri',
                price: 3000,
                totalSlots: 8,
                availableSlots: 2,
                organizerId: sam._id,
                isTournament: true,
                coordinates: { lat: 12.7409, lng: 77.8253 },
            },

            // --- Mayiladuthurai ---
            {
                title: 'Mayiladuthurai Badminton Open',
                sport: 'badminton',
                description: 'Open badminton tournament for all age groups.\n\nCategories: U-15, U-19, Open\nEntry: ₹150',
                date: new Date('2026-05-20T09:00:00'),
                location: 'Town Hall Complex, Mayiladuthurai',
                district: 'Mayiladuthurai',
                price: 150,
                totalSlots: 32,
                availableSlots: 20,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 11.1014, lng: 79.6551 },
            },
            {
                title: 'Casual Cricket at Mayiladuthurai',
                sport: 'cricket',
                description: 'Sunday morning cricket. Looking for players!\n\nT10 format, 6-a-side.',
                date: new Date('2026-06-14T06:30:00'),
                location: 'Government School Ground, Mayiladuthurai',
                district: 'Mayiladuthurai',
                price: 0,
                totalSlots: 12,
                availableSlots: 7,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 11.1020, lng: 79.6560 },
            },

            // --- Nagapattinam ---
            {
                title: 'Nagapattinam Beach Football',
                sport: 'football',
                description: 'Beach football tournament near the coast. Fun, sand, and football!\n\nFormat: 5-a-side Beach\nEntry: Free',
                date: new Date('2026-05-30T06:00:00'),
                location: 'Nagapattinam Beach',
                district: 'Nagapattinam',
                price: 0,
                totalSlots: 10,
                availableSlots: 6,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 10.7672, lng: 79.8449 },
            },
            {
                title: 'Nagapattinam District Basketball',
                sport: 'basketball',
                description: 'District basketball tournament for youth players.\n\nU-21 category\nPrize: Medals + Certificate',
                date: new Date('2026-06-08T09:00:00'),
                location: 'District Sports Complex, Nagapattinam',
                district: 'Nagapattinam',
                price: 0,
                totalSlots: 8,
                availableSlots: 4,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 10.7670, lng: 79.8420 },
            },

            // --- Namakkal ---
            {
                title: 'Namakkal Lorry Kings Cricket',
                sport: 'cricket',
                description: 'Cricket tournament organized by the Lorry Owners Association.\n\nFormat: T20\nOpen to all\nPrize Pool: ₹35,000',
                date: new Date('2026-05-04T07:00:00'),
                location: 'VOC Stadium, Namakkal',
                district: 'Namakkal',
                price: 500,
                totalSlots: 12,
                availableSlots: 5,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 11.2189, lng: 78.1674 },
            },
            {
                title: 'Namakkal Sunday Football',
                sport: 'football',
                description: 'Casual Sunday evening football. All ages welcome. Bring your friends!',
                date: new Date('2026-05-25T16:00:00'),
                location: 'Town Ground, Namakkal',
                district: 'Namakkal',
                price: 0,
                totalSlots: 14,
                availableSlots: 8,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 11.2200, lng: 78.1680 },
            },

            // --- Nilgiris ---
            {
                title: 'Ooty Hill Station Badminton Open',
                sport: 'badminton',
                description: 'Play badminton in the Queen of Hill Stations! Open tournament with stunning views.\n\nCategories: Open Singles & Doubles\nEntry: ₹300',
                date: new Date('2026-05-22T10:00:00'),
                location: 'Municipal Indoor Court, Ooty',
                district: 'Nilgiris',
                price: 300,
                totalSlots: 24,
                availableSlots: 16,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 11.4102, lng: 76.6950 },
            },
            {
                title: 'Coonoor Football Pickup',
                sport: 'football',
                description: 'Weekly football game in the hills of Coonoor. Cool weather guaranteed! ⛰️',
                date: new Date('2026-06-06T15:00:00'),
                location: 'Sim\'s Park Ground, Coonoor',
                district: 'Nilgiris',
                price: 0,
                totalSlots: 14,
                availableSlots: 10,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 11.3530, lng: 76.7959 },
            },

            // --- Perambalur ---
            {
                title: 'Perambalur Cricket Shield',
                sport: 'cricket',
                description: 'Inter-zone cricket tournament for Perambalur district.\n\nFormat: T20\nPrize: ₹12,000 + Shield',
                date: new Date('2026-05-18T07:30:00'),
                location: 'Government Stadium, Perambalur',
                district: 'Perambalur',
                price: 100,
                totalSlots: 8,
                availableSlots: 4,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 11.2320, lng: 78.8843 },
            },
            {
                title: 'Perambalur Evening Basketball',
                sport: 'basketball',
                description: 'Casual evening basketball. 3x3 half-court. Beginners welcome!',
                date: new Date('2026-06-12T17:30:00'),
                location: 'Government Boys School Court, Perambalur',
                district: 'Perambalur',
                price: 0,
                totalSlots: 12,
                availableSlots: 8,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 11.2330, lng: 78.8850 },
            },

            // --- Pudukkottai ---
            {
                title: 'Pudukkottai Palace Cup Football',
                sport: 'football',
                description: 'Historic Palace Cup football tournament.\n\nFormat: 7-a-side\nOpen to all local clubs\nPrize: Trophy + ₹20,000',
                date: new Date('2026-05-12T08:00:00'),
                location: 'Palace Ground, Pudukkottai',
                district: 'Pudukkottai',
                price: 200,
                totalSlots: 16,
                availableSlots: 10,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 10.3833, lng: 78.8001 },
            },
            {
                title: 'Pudukkottai Badminton Club Night',
                sport: 'badminton',
                description: 'Weekly badminton club night. Play doubles under the lights.\n\nAll skill levels. Bring your racket!',
                date: new Date('2026-06-04T19:00:00'),
                location: 'District Badminton Hall, Pudukkottai',
                district: 'Pudukkottai',
                price: 50,
                totalSlots: 16,
                availableSlots: 10,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 10.3840, lng: 78.8010 },
            },

            // --- Ramanathapuram ---
            {
                title: 'Ramanathapuram Maritime Cricket Cup',
                sport: 'cricket',
                description: 'Cricket tournament for fishing community teams and others.\n\nFormat: T20\nPrize: ₹15,000',
                date: new Date('2026-05-20T07:00:00'),
                location: 'Government Ground, Ramanathapuram',
                district: 'Ramanathapuram',
                price: 0,
                totalSlots: 8,
                availableSlots: 5,
                organizerId: raj._id,
                isTournament: true,
                coordinates: { lat: 9.3639, lng: 78.8395 },
            },
            {
                title: 'Rameswaram Beach Basketball',
                sport: 'basketball',
                description: 'Beach basketball event near the famous temple town.\n\n3x3 format. Open to all.',
                date: new Date('2026-06-15T06:00:00'),
                location: 'Rameswaram Beach Side Court',
                district: 'Ramanathapuram',
                price: 0,
                totalSlots: 12,
                availableSlots: 8,
                organizerId: priya._id,
                isTournament: false,
                coordinates: { lat: 9.2876, lng: 79.3129 },
            },

            // --- Ranipet ---
            {
                title: 'Ranipet Industrial Football Cup',
                sport: 'football',
                description: 'Football tournament organized by factory workers associations.\n\nFormat: 7-a-side\nPrize: ₹20,000',
                date: new Date('2026-05-06T08:00:00'),
                location: 'Municipal Stadium, Ranipet',
                district: 'Ranipet',
                price: 100,
                totalSlots: 16,
                availableSlots: 8,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 12.9321, lng: 79.3330 },
            },
            {
                title: 'Ranipet Weekend Cricket',
                sport: 'cricket',
                description: 'Casual weekend cricket matches. Join as individual or team.\n\nFormat: T10 Box Cricket',
                date: new Date('2026-06-13T07:00:00'),
                location: 'Town Grounds, Ranipet',
                district: 'Ranipet',
                price: 0,
                totalSlots: 12,
                availableSlots: 6,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 12.9330, lng: 79.3340 },
            },

            // --- Sivagangai ---
            {
                title: 'Sivagangai Royal Cricket Trophy',
                sport: 'cricket',
                description: 'Named after the historic Sivagangai Kingdom. T20 tournament.\n\nPrize: Trophy + ₹18,000',
                date: new Date('2026-05-14T07:30:00'),
                location: 'Sivagangai District Ground',
                district: 'Sivagangai',
                price: 200,
                totalSlots: 8,
                availableSlots: 4,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 10.2800, lng: 78.6200 },
            },
            {
                title: 'Sivagangai Badminton Night',
                sport: 'badminton',
                description: 'Friday night badminton sessions. Play under floodlights!',
                date: new Date('2026-06-05T19:00:00'),
                location: 'Indoor Hall, Sivagangai',
                district: 'Sivagangai',
                price: 0,
                totalSlots: 16,
                availableSlots: 12,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 10.2810, lng: 78.6210 },
            },

            // --- Tenkasi ---
            {
                title: 'Tenkasi Courtallam Cup Football',
                sport: 'football',
                description: 'Football tournament near the famous waterfalls of Courtallam.\n\nFormat: 7-a-side\nPrize: ₹12,000',
                date: new Date('2026-05-28T08:00:00'),
                location: 'Municipal Ground, Tenkasi',
                district: 'Tenkasi',
                price: 100,
                totalSlots: 12,
                availableSlots: 7,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 8.9580, lng: 77.3152 },
            },
            {
                title: 'Tenkasi Community Basketball',
                sport: 'basketball',
                description: 'Community basketball games every Saturday morning. Open to all.',
                date: new Date('2026-06-13T06:30:00'),
                location: 'Government School Court, Tenkasi',
                district: 'Tenkasi',
                price: 0,
                totalSlots: 10,
                availableSlots: 6,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 8.9590, lng: 77.3160 },
            },

            // --- Thanjavur ---
            {
                title: 'Thanjavur Big Temple Cricket League',
                sport: 'cricket',
                description: 'Premier cricket league in the cultural capital. Multi-weekend T20.\n\nPrize Pool: ₹45,000\nTeams: 10',
                date: new Date('2026-04-27T07:00:00'),
                location: 'Raja Serfoji College Ground, Thanjavur',
                district: 'Thanjavur',
                price: 800,
                totalSlots: 10,
                availableSlots: 4,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 10.7870, lng: 79.1378 },
            },
            {
                title: 'Thanjavur College Basketball',
                sport: 'basketball',
                description: 'Inter-college basketball tournament for Thanjavur zone colleges.\n\nFormat: 5v5\nPrize: Medals + Certificate',
                date: new Date('2026-06-10T15:00:00'),
                location: 'Periya Maligai Sports Hall, Thanjavur',
                district: 'Thanjavur',
                price: 0,
                totalSlots: 12,
                availableSlots: 6,
                organizerId: raj._id,
                isTournament: true,
                coordinates: { lat: 10.7880, lng: 79.1390 },
            },

            // --- Theni ---
            {
                title: 'Theni Hill Station Football Challenge',
                sport: 'football',
                description: 'Football challenge in the foothills of Western Ghats.\n\nFormat: 5-a-side\nEntry: Free',
                date: new Date('2026-05-19T07:30:00'),
                location: 'Municipal Stadium, Theni',
                district: 'Theni',
                price: 0,
                totalSlots: 10,
                availableSlots: 6,
                organizerId: alex._id,
                isTournament: false,
                coordinates: { lat: 10.0104, lng: 77.4768 },
            },
            {
                title: 'Theni Cricket Knockout',
                sport: 'cricket',
                description: 'Quick-fire knockout cricket tournament. T10 format.\n\nTeams: 8\nPrize: ₹8,000',
                date: new Date('2026-06-09T08:00:00'),
                location: 'Andipatti Grounds, Theni',
                district: 'Theni',
                price: 100,
                totalSlots: 8,
                availableSlots: 4,
                organizerId: sam._id,
                isTournament: true,
                coordinates: { lat: 10.0110, lng: 77.4780 },
            },

            // --- Thoothukudi (Tuticorin) ---
            {
                title: 'Tuticorin Port City Basketball League',
                sport: 'basketball',
                description: 'Port City Basketball League. 5v5 full court.\n\nOpen to all Thoothukudi residents.\nPrize Pool: ₹20,000',
                date: new Date('2026-05-13T16:00:00'),
                location: 'VOC Stadium, Thoothukudi',
                district: 'Thoothukudi (Tuticorin)',
                price: 0,
                totalSlots: 12,
                availableSlots: 5,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 8.7642, lng: 78.1348 },
            },
            {
                title: 'Tuticorin Beach Cricket',
                sport: 'cricket',
                description: 'Casual beach cricket near the harbor. All ages welcome.\n\nBring your own gear!',
                date: new Date('2026-06-07T06:00:00'),
                location: 'Harbour Beach, Thoothukudi',
                district: 'Thoothukudi (Tuticorin)',
                price: 0,
                totalSlots: 0,
                availableSlots: 0,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 8.7650, lng: 78.1360 },
            },

            // --- Tirunelveli ---
            {
                title: 'Nellai Football Championship',
                sport: 'football',
                description: 'Inter-zone football championship for Tirunelveli district.\n\nFormat: 11-a-side\nPrize: ₹35,000',
                date: new Date('2026-05-08T08:00:00'),
                location: 'VOC Ground, Tirunelveli',
                district: 'Tirunelveli',
                price: 300,
                totalSlots: 16,
                availableSlots: 8,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 8.7139, lng: 77.7567 },
            },
            {
                title: 'Tirunelveli Badminton Social',
                sport: 'badminton',
                description: 'Weekly badminton social. Meet new players, have fun!\n\nTuesday & Thursday evenings.',
                date: new Date('2026-05-26T18:00:00'),
                location: 'Indoor Stadium, Tirunelveli',
                district: 'Tirunelveli',
                price: 0,
                totalSlots: 20,
                availableSlots: 14,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 8.7140, lng: 77.7570 },
            },

            // --- Tirupathur ---
            {
                title: 'Tirupathur Inter-School Cricket',
                sport: 'cricket',
                description: 'Annual inter-school cricket tournament.\n\nFormat: T20\nCategories: Boys & Girls',
                date: new Date('2026-05-07T08:00:00'),
                location: 'Government School Ground, Tirupathur',
                district: 'Tirupathur',
                price: 0,
                totalSlots: 12,
                availableSlots: 6,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 12.4952, lng: 78.5733 },
            },
            {
                title: 'Tirupathur Casual Football',
                sport: 'football',
                description: 'Weekly casual football game. All skill levels welcome.',
                date: new Date('2026-06-11T17:00:00'),
                location: 'Town Ground, Tirupathur',
                district: 'Tirupathur',
                price: 0,
                totalSlots: 14,
                availableSlots: 10,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 12.4960, lng: 78.5740 },
            },

            // --- Tiruppur ---
            {
                title: 'Tiruppur Textile City Cricket Cup',
                sport: 'cricket',
                description: 'Cricket tournament for textile industry workers and enthusiasts.\n\nFormat: T20\nPrize Pool: ₹50,000',
                date: new Date('2026-05-02T07:00:00'),
                location: 'Tiruppur Municipal Ground',
                district: 'Tiruppur',
                price: 500,
                totalSlots: 12,
                availableSlots: 4,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 11.1085, lng: 77.3411 },
            },
            {
                title: 'Tiruppur Hoopsters — Basketball',
                sport: 'basketball',
                description: 'Evening basketball pickup games. 3x3 and 5v5 available.\n\nAll welcome!',
                date: new Date('2026-05-29T17:00:00'),
                location: 'YMCA Court, Tiruppur',
                district: 'Tiruppur',
                price: 0,
                totalSlots: 10,
                availableSlots: 6,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 11.1090, lng: 77.3420 },
            },

            // --- Tiruvallur ---
            {
                title: 'Tiruvallur Football Fiesta',
                sport: 'football',
                description: 'District-level football competition. Exciting matches every weekend.\n\nFormat: 7-a-side\nPrize: ₹18,000',
                date: new Date('2026-05-15T08:30:00'),
                location: 'District Stadium, Tiruvallur',
                district: 'Tiruvallur',
                price: 200,
                totalSlots: 16,
                availableSlots: 10,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 13.1437, lng: 79.9121 },
            },
            {
                title: 'Tiruvallur Badminton Meetup',
                sport: 'badminton',
                description: 'Casual badminton meetup at the new indoor facility. Coaching available.\n\nEvery Wednesday evening.',
                date: new Date('2026-06-03T18:00:00'),
                location: 'Indoor Sports Hall, Tiruvallur',
                district: 'Tiruvallur',
                price: 0,
                totalSlots: 16,
                availableSlots: 12,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 13.1440, lng: 79.9130 },
            },

            // --- Tiruvannamalai ---
            {
                title: 'Girivalam Cricket Trophy',
                sport: 'cricket',
                description: 'Cricket tournament inspired by the sacred Girivalam path.\n\nFormat: T20\nPrize: ₹20,000 + Trophy',
                date: new Date('2026-05-21T07:00:00'),
                location: 'Government Ground, Tiruvannamalai',
                district: 'Tiruvannamalai',
                price: 300,
                totalSlots: 10,
                availableSlots: 5,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 12.2253, lng: 79.0747 },
            },
            {
                title: 'Tiruvannamalai Basketball Jam',
                sport: 'basketball',
                description: 'Weekend basketball jam. 3x3 tournament + freestyle skills contest.\n\nEntry: Free',
                date: new Date('2026-06-14T16:00:00'),
                location: 'Arts College Court, Tiruvannamalai',
                district: 'Tiruvannamalai',
                price: 0,
                totalSlots: 12,
                availableSlots: 8,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 12.2260, lng: 79.0750 },
            },

            // --- Tiruvarur ---
            {
                title: 'Tiruvarur Temple Town Football',
                sport: 'football',
                description: 'Football tournament in the temple town of Tiruvarur.\n\nFormat: 7-a-side\nPrize: ₹10,000',
                date: new Date('2026-05-16T08:00:00'),
                location: 'Corporation Ground, Tiruvarur',
                district: 'Tiruvarur',
                price: 100,
                totalSlots: 12,
                availableSlots: 6,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 10.7725, lng: 79.6370 },
            },
            {
                title: 'Tiruvarur Evening Cricket',
                sport: 'cricket',
                description: 'Casual evening cricket under lights. All skill levels welcome.',
                date: new Date('2026-06-08T17:30:00'),
                location: 'Town Ground, Tiruvarur',
                district: 'Tiruvarur',
                price: 0,
                totalSlots: 14,
                availableSlots: 10,
                organizerId: raj._id,
                isTournament: false,
                coordinates: { lat: 10.7730, lng: 79.6380 },
            },

            // --- Vellore ---
            {
                title: 'VIT Vellore Inter-College Football Cup',
                sport: 'football',
                description: 'VIT Vellore hosts the Inter-College Football Cup.\n\nFormat: 11-a-side\nOpen to all Tamil Nadu colleges\nPrize Pool: ₹50,000',
                date: new Date('2026-05-03T09:00:00'),
                location: 'VIT University Ground, Vellore',
                district: 'Vellore',
                price: 400,
                totalSlots: 16,
                availableSlots: 6,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 12.9692, lng: 79.1559 },
            },
            {
                title: 'Vellore Fort Cricket Challenge',
                sport: 'cricket',
                description: 'Cricket challenge near the historic Vellore Fort.\n\nFormat: T10\nOpen to all',
                date: new Date('2026-06-01T07:00:00'),
                location: 'Vellore Fort Ground',
                district: 'Vellore',
                price: 0,
                totalSlots: 8,
                availableSlots: 4,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 12.9165, lng: 79.1325 },
            },

            // --- Viluppuram ---
            {
                title: 'Viluppuram District Football League',
                sport: 'football',
                description: 'District football league. All local clubs eligible.\n\nFormat: 11-a-side League\nPrize: ₹25,000',
                date: new Date('2026-05-10T08:00:00'),
                location: 'District Sports Complex, Viluppuram',
                district: 'Viluppuram',
                price: 200,
                totalSlots: 12,
                availableSlots: 6,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 11.9395, lng: 79.4924 },
            },
            {
                title: 'Viluppuram Badminton Doubles',
                sport: 'badminton',
                description: 'Doubles badminton tournament. Find a partner and compete!\n\nEntry: ₹100 per pair',
                date: new Date('2026-06-06T09:30:00'),
                location: 'Indoor Stadium, Viluppuram',
                district: 'Viluppuram',
                price: 100,
                totalSlots: 24,
                availableSlots: 16,
                organizerId: raj._id,
                isTournament: true,
                coordinates: { lat: 11.9400, lng: 79.4930 },
            },

            // --- Virudhunagar ---
            {
                title: 'Virudhunagar Match King Cricket Cup',
                sport: 'cricket',
                description: 'Named after the famous match industry. T20 cricket tournament.\n\nPrize Pool: ₹30,000\nTeams: 10',
                date: new Date('2026-05-08T07:30:00'),
                location: 'Municipal Corporation Ground, Virudhunagar',
                district: 'Virudhunagar',
                price: 400,
                totalSlots: 10,
                availableSlots: 4,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 9.5855, lng: 77.9525 },
            },
            {
                title: 'Virudhunagar Pickup Basketball',
                sport: 'basketball',
                description: 'Casual basketball every Saturday afternoon. All levels welcome!',
                date: new Date('2026-06-13T15:00:00'),
                location: 'Government Boys School Court, Virudhunagar',
                district: 'Virudhunagar',
                price: 0,
                totalSlots: 10,
                availableSlots: 6,
                organizerId: sam._id,
                isTournament: false,
                coordinates: { lat: 9.5860, lng: 77.9530 },
            },

            // ══════════════════════════════════════════════════════════════
            // EXTRA — Additional events for variety in key districts
            // ══════════════════════════════════════════════════════════════

            // --- Madurai (extra) ---
            {
                title: 'Madurai Meenakshi Cricket League',
                sport: 'cricket',
                description: 'Premier cricket league in the temple city. Multi-weekend T20.\n\nPrize Pool: ₹60,000\nTeams: 12',
                date: new Date('2026-04-22T07:00:00'),
                location: 'Tamukkam Grounds, Madurai',
                district: 'Madurai',
                price: 1000,
                totalSlots: 12,
                availableSlots: 5,
                organizerId: priya._id,
                isTournament: true,
                coordinates: { lat: 9.9300, lng: 78.1200 },
            },

            // --- Salem (extra) ---
            {
                title: 'Salem Steel City Badminton Open',
                sport: 'badminton',
                description: 'Open badminton tournament in Salem. All age categories.\n\nCategories: U-15, U-19, Open, Veterans\nEntry: ₹250',
                date: new Date('2026-05-14T09:00:00'),
                location: 'Yercaud Indoor Hall, Salem',
                district: 'Salem',
                price: 250,
                totalSlots: 48,
                availableSlots: 30,
                organizerId: raj._id,
                isTournament: true,
                coordinates: { lat: 11.6650, lng: 78.1470 },
            },

            // --- Tiruchirappalli (extra) ---
            {
                title: 'Trichy Rock Fort Basketball Cup',
                sport: 'basketball',
                description: 'Inter-college basketball cup organized by NIT Trichy.\n\nFormat: 5v5\nOpen to all colleges in TN\nPrize: ₹30,000',
                date: new Date('2026-06-02T15:30:00'),
                location: 'NIT Trichy Sports Complex',
                district: 'Tiruchirappalli',
                price: 0,
                totalSlots: 16,
                availableSlots: 8,
                organizerId: alex._id,
                isTournament: true,
                coordinates: { lat: 10.7600, lng: 78.8139 },
            },
        ]);

        console.log(`✅ ${events.length} events created`);
        console.log('\n========================================');
        console.log('  SAMPLE LOGIN CREDENTIALS');
        console.log('========================================');
        console.log('  User 1:');
        console.log('    Email:    alex@interplay.com');
        console.log('    Password: password123');
        console.log('');
        console.log('  User 2:');
        console.log('    Email:    sam@interplay.com');
        console.log('    Password: password123');
        console.log('');
        console.log('  User 3:');
        console.log('    Email:    priya@interplay.com');
        console.log('    Password: password123');
        console.log('');
        console.log('  User 4:');
        console.log('    Email:    raj@interplay.com');
        console.log('    Password: password123');
        console.log('========================================\n');

        console.log('Done! Database seeded successfully.');
    } catch (err) {
        console.error('Seed error:', err);
    }
};

module.exports = seedData;
